# ------------------------------------------------------------------------------
#           _           _                            _
# __      _(_)_ __   __| | _____      __  _ __ _   _| | ___  ___
# \ \ /\ / / | '_ \ / _` |/ _ \ \ /\ / / | '__| | | | |/ _ \/ __|
#  \ V  V /| | | | | (_| | (_) \ V  V /  | |  | |_| | |  __/\__ \
#   \_/\_/ |_|_| |_|\__,_|\___/ \_/\_/   |_|   \__,_|_|\___||___/
# ------------------------------------------------------------------------------

# to know the class of current open windows run:
# $ hyprctl clients

# specify workspaces for some applications
windowrule = workspace 2, opacity 0.85, title:^(.*LibreWolf.*)$
windowrule = workspace 3, title:^(.*FreeCAD.*)$
windowrule = float, title:(FreeCAD)(.*)$ # for splashscreen but affects application
windowrule = workspace 4, title:^(.*kicad.*)$
windowrule = float, title:^(.*kicad.*)$
windowrule = workspace 4, title:(Qt Linguist)
windowrule = workspace 5, title:(Qt Designer)
windowrule = workspace 5, title:^(.*Logseq.*)$
windowrule = workspace 7, title:^(.*Element.*)$
windowrule = workspace 7, title:^(.*whatsdesk.*)$
windowrule = workspace 7, title:^(.*telegram.*)$
windowrule = workspace 8, title:^(.*thunderbird.*)$
windowrule = opacity 0.5, title:^(.*mousepad.*)$
#windowrule = workspace 9, title:^(.*discord.*)$
windowrule = workspace 9, title:^(.*lollypop.*)$
windowrule = float, title:^(.*lollypop.*)$
windowrule = workspace 9, title:^(.*mpv.*)$
windowrule = float, title:^(.*mpv.*)$
windowrule = workspace 9, title:^(.*Spotify.*)$
windowrule = workspace 10, title:^(.*Xonotic.*)$

# some floating windows
windowrule = float, title:^(nm-connection-editor)$
windowrule = float, title:^(zenity)$
windowrule = float, title:^(gmrun)$
windowrule = float, title:^(.*thunar.*)$
windowrule = float, title:^(New Text Note — Okular)$
windowrule = float, title:^(org.gnome.Nautilus New Folder)$

windowrule = float, title:(Choose.*a.*)$
windowrule = move center, title:(Choose.*a.*)$
windowrule = size 850 500, title:(Choose.*a.*)$
windowrule = float, title:(New.*File.*)$
windowrule = move center, title:(New.*File.*)$
windowrule = size 850 500, title:(New.*File.*)$
windowrule = float, title:(Open.*File.*)$
windowrule = move center, title:(Open.*File.*)$
windowrule = size 850 500, title:(Open.*File.*)$
windowrule = float, title:(Open Form)(.*)$
windowrule = move center, title:(Open Form)(.*)$
windowrule = size 850 500, title:(Open Form)(.*)$
windowrule = float, title:(Preferences.*)$
windowrule = move center, title:(Preferences.*)$
windowrule = size 850 500, title:(Preferences.*)$
windowrule = float, title:(Export Image as.*)$
windowrule = move center, title:(Export Image as.*)$
windowrule = size 650 600, title:(Export Image as.*)$

# opacity selected no_selected
windowrulev2 = opacity 0.9 0.75, class:^(org.gnome.Nautilus)$
windowrulev2 = opacity 0.9 0.75, class:^(org.gnome.baobab)$
windowrulev2 = opacity 0.9 0.75, class:^(org.gnome.clocks)$
windowrulev2 = opacity 0.9 0.75, class:^(gnome.pomodoro)$
windowrulev2 = opacity 0.9 0.75, class:^(czkawka-gui)$
windowrulev2 = opacity 0.75 0.75, class:^(.*Alacritty.*)$
windowrulev2 = opacity 0.50 0.75, class:^(.*thunar.*)$
windowrulev2 = opacity 0.75 0.75, class:^(.*terminal.*)$
windowrulev2 = opacity 0.85 0.75, class:^(.*librewolf.*)$
windowrulev2 = opacity 0.50 0.75, class:^(.*mousepad.*)$
windowrulev2 = opacity 0.75 0.75, class:^(.*discord.*)$
windowrulev2 = opacity 0.75 0.75, class:^(.*Element.*)$
windowrulev2 = opacity 0.50 0.75, class:^(.*KeePass.*)$
windowrulev2 = opacity 0.50 0.75, class:^(.*signal.*)$
windowrulev2 = opacity 0.50 0.75, class:^(.*kleopatra.*)$
windowrulev2 = opacity 0.50 0.75, class:^(.*variety.*)$

