#!/usr/bin/env bash

DIR="$HOME/Pictures/Screenshots"
FILENAME="$DIR/Screenshot_$(date +"%Y-%m-%d_%H-%M-%S").png"

# grim -g "$(slurp)" - | wl-copy
function selection() {
	grim -g "$(slurp)" - | swappy -f - -o $FILENAME
}

# function full_screen() {
# 	grim -g "$(slurp -o)" - | swappy -f - -o $FILENAME
# }

function full_screen() {
	grim - | swappy -f - -o $FILENAME
}

function delay() {
	geo="$(slurp)"
	sleep 3
	grim -g "$geo" - | swappy -f - -o $FILENAME
}

doc() {
	echo "Usage:
    screenshot [Options]

    Options:
        selection       Screenshots the selected area
        full_screen     Screenshots the focussed screen
        all_screens     Screenshots all screens
        delay           Takes a screenshot of the selected area after 3 second"
}

case $1 in
selection) selection ;;
full_screen) full_screen ;;
all_screens) all_screens ;;
delay) delay ;;
*) doc ;;
esac
